<?php

/**
 * @file
 * adds a formatter for Address Field fields that creates a link to maps.google.com
 */

/**
 * Implements hook_field_formatter_info().
 */
function gmaplink_field_formatter_info () {
  return array(
      'gmaplink_formatter' => array(
        'label' => t('Google Map Link'),
        'field types' => array('addressfield'),
        'settings' => array(
          'display_type' => array('text'),
          'link_text' => array('Go to map'),
          'addr_parts_display' => array('thoroughfare'),
          ),
        ),
      );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function gmaplink_field_formatter_settings_form ($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  $element['display_type'] = array(
      '#type' => 'radios',
      '#title' => t('Display type'),
      '#description' => t("Select 'Custom text' and enter text into the 'Link text' field, or select 'Address parts' and select the address parts to display."),
      '#default_value' => $settings['display_type'],
      '#required' => TRUE,
      '#options' => array(
        'text' => t('Custom text'),
        'addr_parts' => t('Address parts'),
        ),
      );
  $element['link_text'] = array(
      '#type' => 'textfield',
      '#title' => t('Link text'),
      '#description' => t('This will be the text that the user clicks on to go to the Google map.'),
      '#default_value' => $settings['link_text'],
      );
  $element['addr_parts_display'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Address parts to display'),
      '#description' => t('Place a checkbox next to each address part to display'),
      '#default_value' => $settings['addr_parts_display'],
      '#options' => array(
        'thoroughfare' => t('Street'),
        'locality' => t('City'),
        'administrative_area' => t('State'),
        'postal_code' => t('Zip code'),
        ),
      );
  return $element;
}

/**
 * Implements hook_field_formatter_setttings_summary().
 */
function gmaplink_field_formatter_settings_summary ($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  dpm($settings);
  if ($settings['display_type'] == 'addr_parts') {
    $summary = t("Render Google map link with address parts.");
  } else {
    $summary = t("Render Google map link with link text '@link_text'.", array(
          '@link_text' => $settings['link_text'],
          ));
  }
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function gmaplink_field_formatter_view ($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  $link_text = $settings['link_text'];

  foreach ($items as $delta => $item) {
    $addr_parts['thoroughfare'] = $item['thoroughfare'];
    $addr_parts['locality'] = $item['locality'];
    $addr_parts['administrative_area'] = $item['administrative_area'];
    $addr_parts['postal_code'] = $item['postal_code'];
  }
  $addr = implode(' ', $addr_parts);

  if ($settings['display_type'] == 'addr_parts') {
    foreach ($settings['addr_parts_display'] as $part) {
      if ($part !== 0) {
        $parts_display[$part] = $part;
      }
    }

    foreach ($parts_display as $delta => $part) {
      $parts_display_parts[$delta] = $addr_parts[$part];
    }
    $link_text = implode(' ', $parts_display_parts);
  }



  $options = array(
      'html' => FALSE,
      );
  $link = l($link_text, "http://maps.google.com/maps?q=" . urlencode($addr));
  $element[0]['#markup'] = $link;
  return $element;

}
