<?php

/**
 * @file
 * Module to use nodes as dropdown menus.
 */

/**
 * Implementation of hook_menu().
 */
function nice_mega_dropdowns_menu() {
  $items['nice_mega_dropdowns/autocomplete'] = array(
    'title' => 'Autocomplete results for Nice Mega Dropdowns',
    'page callback' => 'nice_mega_dropdowns_autocomplete',
    'page arguments' => array(2),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function nice_mega_dropdowns_form_menu_edit_item_alter(&$form, &$form_state, $form_id) {
  $dropdowns = variable_get('nice_mega_dropdowns', 0);
  $mlid = $form['mlid']['#value'];
  $form['menu']['dropdown'] = array(
    '#type' => 'textfield',
    '#title' => 'Dropdown',
    '#default_value' => $dropdowns[$mlid],
    '#autocomplete_path' => 'nice_mega_dropdowns/autocomplete',
    '#required' => FALSE,
    '#description' => 'Select a mega dropdown node, which will be displayed instead of child menu items.',
    '#tree' => TRUE,
  '#access' => TRUE
  );

  $form['#validate'][] = 'nice_mega_dropdowns_menu_edit_item_validate';
  $form['#submit'][] = 'nice_mega_dropdowns_menu_edit_item_submit';
}

function nice_mega_dropdowns_menu_edit_item_validate(&$form, &$form_state) {
  if (empty($form_state['values']['dropdown'])) {
    return;
  }
  $node = node_load($form_state['values']['dropdown']);
  if (!$node->status) {
    form_set_error('dropdown', 'Invalid node.');
  }
}

function nice_mega_dropdowns_menu_edit_item_submit(&$form, &$form_state) {
  $dropdowns = variable_get('nice_mega_dropdowns', 0);
  if (!$dropdowns) {
    $dropdowns = array();
  }
  $dropdowns[$form_state['values']['mlid']] = $form_state['values']['dropdown'];
  variable_set('nice_mega_dropdowns', $dropdowns);
}

function nice_mega_dropdowns_autocomplete($string) {
  $items = array();
  $string = $string . '%%';
  $result = db_query("SELECT nid, title FROM {node} WHERE status = 1 AND title LIKE :string", array(':string' => $string));
  foreach ($result as $record) {
    $items[$record->nid] = $record->title;
  }
  print drupal_json_output($items);
  exit();
}

function nice_mega_dropdowns_get_dropdown($menu_item) {
  $dropdowns = variable_get('nice_mega_dropdowns', array());
  $mlid = $menu_item['link']['mlid'];
  if ($nid = $dropdowns[$mlid]) {
    $node = node_load($nid);
    $body = field_view_field('node', $node, 'body');
    if ($node->status == 1) {
      return $body[0]['#markup'];
    }
  }
  else {
    return FALSE;
  }
}
